name: condition-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  conditional-steps:
    name: Conditional Steps

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Rustup Check
      id: rustup-check
      run: |
        rustup -v || exit 1 
      continue-on-error: true
     
    - name: Rustup Exists?
      id: rustup-exists
      if: ${{ steps.rustup-check.outcome == 'success' }}
      run: echo "Rustup does exist."

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.69.0
      with:
        target: wasm32-unknown-unknown
        components: clippy
    
    - name: Invalid Command Check
      id: invalid-command
      run: |
        invalid_command || exit 1
      continue-on-error: true
       
    - name: Invalid-command Exists?
      id: invalid-command-check
      if: ${{ steps.invalid-command.outcome == 'failure' }}
      run: echo "invalid-command does not exist."