name: condition-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  conditional-steps:
    name: Conditional Steps

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Rustup Check
      id: rustup-check
      shell: bash
      run: |
        if ! command -v rustup &> /dev/null ; then
          echo "has-rustup=false" >> $GITHUB_OUTPUT
        else
          echo "has-rustup=true" >> $GITHUB_OUTPUT
        fi
     
    - name: Rustup Exists?
      id: rustup-exists
      if: steps.rustup-check.outputs.has-rustup
      run: echo "Rustup does exist."

    - name: Invalid Command Check
      id: invalid-command-check
      shell: bash
      run: |
        if ! command -v foobar &> /dev/null ; then
          echo "has-foobar=false" >> $GITHUB_OUTPUT
        else
          echo "has-foobar=true" >> $GITHUB_OUTPUT
        fi
       
    - name: Command Exists?
      id: command-exists
      if: steps.invalid-command-check.outputs.has-foobar
      run: echo "Foobar does exist."